---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hs
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  clusterIP: None
  ports:
  - name: '9092'
    port: 9092
{{- range $i, $e := until (.Values.replicas | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-cs-{{$i}}
  namespace: '{{ $.Release.Namespace }}'
  labels:
    app: {{ $.Release.Name }}
spec:
  selector:
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-{{$i}}
  type: NodePort
  ports:
  - name: '9092'
    port: 9092
    targetPort: 9092
    nodePort: 909{{add 2 $i}}
{{end}}