version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.{{ param_role_name }}.rule: Host(`wordpress.czy21.com`)
  traefik.http.routers.{{ param_role_name }}.service: {{ param_role_name }}
  traefik.http.services.{{ param_role_name }}.loadbalancer.server.port: 80

services:
  wordpress:
    image: wordpress
    container_name: wordpress
    labels:
      <<: *traefik-label
    privileged: true
    user: root
    expose:
      - "80"
    volumes:
      - {{ param_docker_data }}/{{ param_role_name }}/data/:/var/www/html
    environment:
      WORDPRESS_DB_HOST: 192.168.2.18
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: ***REMOVED***
      WORDPRESS_DB_NAME: wordpress
    restart: always