http:
  routers:
    radarr:
      rule: Host(`radarr.czy21.com`)
      service: radarr@docker
    sonarr:
      rule: Host(`sonarr.czy21.com`)
      service: sonarr@docker
    bazarr:
      rule: Host(`bazarr.czy21.com`)
      service: bazarr@docker
    chinesesubfinder:
      rule: Host(`chinesesubfinder.czy21.com`)
      service: chinesesubfinder@docker