ks-installer:
  image:
    repository: {{ param_registry_proxy_url }}/kubesphere/ks-installer
    tag: v3.3.1
  cc:
    authentication:
      jwtSecret: "{{ param_ks_jwt }}"
    multicluster:
      clusterRole: {{ param_ks_role | default("none") }} # host | member | none
    common:
      es:
        logMaxAge: 7
        elkPrefix: {{ param_cluster_name }}
        basicAuth:
          enabled: true
          username: {{ param_db_es_username }}
          password: {{ param_db_es_password }}
        externalElasticsearchUrl: {{ param_db_es_host }}
        externalElasticsearchPort: {{ param_db_es_port }}
    events:
      enabled: true
      ruler:
        enabled: true
        replicas: 1
    logging:
      enabled: true
      logsidecar:
        enabled: true
        replicas: 1
    monitoring:
      prometheus:
       replicas: 1
       volumeSize: 24Gi