- name: k8s join
  become: yes
  shell: kubeadm join 192.168.2.25:6443 --token 1nk6u8.rx29jnazce7k2bdv --discovery-token-ca-cert-hash sha256:8697700c2ce96f42f04c80db32937a3c9ed0b621dfe4be3ed9c139d30c8c20fc