- name: prune
  hosts: all
  remote_user: opsor
  become: yes
  tasks:
    - name: calico prune
      shell: nmcli d status | grep "^cali\|^tun" | awk '{print $1}' | xargs nmcli device delete -
    - name: docker login prune
      shell: rm -rf $HOME/.docker --force
    - name: docker container prune
      shell: docker container prune --force
    - name: docker volume prune
      shell: docker volume prune --force
    - name: docker image prune
      shell: docker image prune --all --force
    - name: docker network prune
      shell: docker network prune --force
    - name: reinstall docker-compose
      shell: rm -rf /usr/local/bin/docker-compose && yum -y install docker-compose-plugin
  tags:
    - prune

- name: machine
  hosts: all
  remote_user: opsor
  vars_files: ["vars/env.yml","vars/main.yml"]
  become: yes
  vars:
    param_users: 
      - root
      - opsor
  tasks:
    - name: passwd -d
      shell: passwd -d {{item}}
      with_items: '{{param_users}}'
    - name: restart docker
      shell: systemctl daemon-reload;systemctl restart docker
    - name: machine reboot
      shell: reboot
    - name: machine shutdown
      shell: shutdown -h now
    - name: kubeadm reset
      shell: sudo kubeadm reset --force --ignore-preflight-errors all;sudo crictl rmi --all;sudo reboot
    - name: k3s uninstall
      shell: /usr/local/bin/k3s-*uninstall.sh;sudo reboot
  tags:
    - machine

- name: manual
  hosts: all
  remote_user: opsor
  vars_files: ["vars/env.yml","vars/main.yml"]
  tasks:
    - name: cmd
      shell: |
        dir
  tags:
    - manual

- name: win
  hosts: all
  remote_user: opsor
  vars_files: ["vars/env.yml","vars/main.yml"]
  tasks:
    - name: cmd
      win_shell: |
        Restart-Computer -Force
  tags:
    - win